### ISSUE TITLE
contoh code pakai bahasa golang

### ISSUE THREAD

**Issue by alghazein** [ummi-codelabs/dasar-pemrograman#69]
gimana kalau tambahin contoh kode pakai golang juga?

## Sample code golang
- [x] #70
- [x] #71
- [x] #72
- [x] #73
- [x] #74
- [x] #75
- [ ] #76

**Comment by doublegunz** [comment]
wah ide bagus tuh..
nanti kita coba tambahkan ya.. atau kalau mau ikutan kontribusi juga diperbolehkan

**Comment by alghazein** [comment]
ok udah a
